version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

  file-proxy:
    image: node:20-alpine
    container_name: file-proxy
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    working_dir: /app
    command: ["node", "file-proxy.js"]
    environment:
      - PROXY_PORT=3000
    depends_on:
      - telegram-bot-api

volumes:
  telegram-bot-api-data: